// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://yfmcirgnxjccjnrjgquv.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmbWNpcmdueGpjY2pucmpncXV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxNDc1MTQsImV4cCI6MjA0ODcyMzUxNH0.WbFoCIJHCeeDMWsg9L3AOaWheeAcuuZia8yEeVbGymo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);